services:
  - type: web
    name: your-backend
    runtime: python
    pythonVersion: 3.10.12
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.simple_app:app
    build:
      cwd: .
